name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  GITPATH: "https://github.com/KozlovNikolai/postgres-chat.git"

jobs:
  deploy-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Selectel cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
#          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          envs: GITPATH
          script: |
            # Setup variables
            # TAG_NAME=$(echo $GITHUB_SHA | head -c7)

            # Login to Docker Registry
            # docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            cd db/db-chat/postgres-chat/
            docker-compose down
            cd ..
            rm -R postgres-chat/
            git clone $GITPATH
            cd postgres-chat/
            docker-compose up -d

            # Stop running container
